package ace.org.epms_backend.enums;

public enum NotificationType {
    // Appraisal Cycle
    APPRAISAL_CYCLE_OPENED,
    APPRAISAL_CYCLE_CLOSED,
    APPRAISAL_CYCLE_REMINDER,
    DEADLINE_REMINDER,

    // Appraisal Process
    APPRAISAL_ASSIGNED,
    SELF_ASSESSMENT_REMINDER,
    SELF_ASSESSMENT_SUBMITTED,
    SELF_ASSESSMENT_OVERDUE,

    MANAGER_EVALUATION_ASSIGNED,
    MANAGER_EVALUATION_REMINDER,
    MANAGER_EVALUATION_SUBMITTED,
    MANAGER_EVALUATION_OVERDUE,

    APPRAISAL_CALCULATED,
    APPRAISAL_SUMMARY_READY,
    APPRAISAL_APPROVED,

    EMPLOYEE_SIGNED_OFF,
    MANAGER_SIGNED_OFF,
    SIGNOFF_PENDING,

    APPRAISAL_LOCKED,
    
    // KPI
    KPI_ASSIGNED,
    KPI_SUBMITTED,
    KPI_APPROVED,
    KPI_REJECTED,
    KPI_REVISED,
    KPI_LOCKED,
    KPI_PROGRESS_UPDATED,

    // Self Assessment (Deprecated or kept for compatibility)
    SELF_ASSESSMENT_OPENED,
    SELF_ASSESSMENT_APPROVED,
    SELF_ASSESSMENT_REJECTED,

    // Feedback
    FEEDBACK_REQUESTED,
    FEEDBACK_REMINDER,
    FEEDBACK_SUBMITTED,

    // Collaboration
    COMMENT_ADDED,
    COMMENT_REPLY,

    // Final Results
    FINAL_RESULT_PUBLISHED,

    // PIP
    PIP_CREATED,
    PIP_UPDATED,
    PIP_REVIEW_DUE,
    PIP_COMPLETED,
    PIP_ESCALATED,

    // Employee & System
    ACCOUNT_ACTIVATED,
    PASSWORD_CHANGED,
    PROFILE_UPDATED,
    SYSTEM
}

