import React from 'react';
import { useAppSelector } from '../../hooks/reduxHooks';
import { useGetMyFeedbackSummaryQuery } from '../../features/feedback360/feedback360Api';
import { useActiveCycle } from '../../context/ActiveCycleContext';
import { 
  BarChart3, 
  Target, 
  MessageCircle, 
  TrendingUp, 
  Star, 
  ShieldCheck,
  LayoutDashboard,
  AlertCircle
} from 'lucide-react';

const MyFeedbackSummary: React.FC = () => {
  const { user } = useAppSelector((state) => state.auth);
  const { activeCycleId } = useActiveCycle();
  
  const cycleId = activeCycleId || 0;
  
  const { data: summary, isLoading, error } = useGetMyFeedbackSummaryQuery(
    { targetUserId: user?.id || 0, cycleId },
    { skip: !user?.id || !cycleId }
  );

  if (isLoading) return (
    <div className="flex flex-col items-center justify-center min-h-[400px] gap-4">
      <div className="w-12 h-12 border-4 border-brand-primary/30 border-t-brand-primary rounded-full animate-spin" />
      <p className="text-text-subtitle font-medium">Aggregating your feedback data...</p>
    </div>
  );

  if (error || !summary) return (
    <div className="bg-brand-primary/5 p-12 rounded-[40px] text-center border border-brand-primary/10 max-w-2xl mx-auto mt-12">
      <div className="w-20 h-20 bg-white rounded-full flex items-center justify-center mx-auto mb-6 shadow-sm border border-brand-primary/10">
        <AlertCircle className="w-10 h-10 text-brand-primary" />
      </div>
      <h3 className="text-2xl font-black text-text-title tracking-tight">Summary Not Yet Available</h3>
      <p className="text-text-subtitle mt-3 max-w-md mx-auto leading-relaxed">
        Your 360° feedback summary for the current cycle is still being processed or has not been generated by HR yet.
      </p>
      <div className="mt-8 flex items-center justify-center gap-4 text-xs font-bold text-text-subtitle uppercase tracking-widest bg-white w-fit mx-auto px-6 py-3 rounded-2xl border border-surface-border">
        <ClockIcon className="w-4 h-4 text-brand-primary" />
        Check back after the cycle ends
      </div>
    </div>
  );

  return (
    <div className="space-y-10 animate-in fade-in zoom-in-95 duration-700">
      {/* Header with Hero Score */}
      <div className="relative bg-gradient-to-br from-brand-primary to-brand-secondary p-8 md:p-12 rounded-[40px] text-white shadow-2xl shadow-brand-primary/20 overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -mr-20 -mt-20 blur-3xl" />
        <div className="absolute bottom-0 left-0 w-48 h-48 bg-black/10 rounded-full -ml-20 -mb-20 blur-2xl" />
        
        <div className="relative flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="text-center md:text-left space-y-2">
            <div className="inline-flex items-center gap-2 bg-white/20 px-3 py-1 rounded-full text-xs font-bold tracking-widest uppercase mb-2">
              <ShieldCheck className="w-3.5 h-3.5" />
              Official Feedback Report
            </div>
            <h1 className="text-4xl md:text-5xl font-black tracking-tight">{summary.targetUserName}</h1>
            <p className="text-white/80 font-medium text-lg">{summary.cycleName} • 360° Assessment</p>
          </div>

          <div className="flex flex-col items-center justify-center">
            <div className="relative w-32 h-32 md:w-40 md:h-40 flex items-center justify-center">
              <svg className="w-full h-full -rotate-90">
                <circle
                  cx="50%" cy="50%" r="45%"
                  className="stroke-white/20 fill-none"
                  strokeWidth="8"
                />
                <circle
                  cx="50%" cy="50%" r="45%"
                  className="stroke-white fill-none"
                  strokeWidth="8"
                  strokeDasharray="283"
                  strokeDashoffset={283 - (283 * summary.totalAverageScore) / 5}
                  strokeLinecap="round"
                />
              </svg>
              <div className="absolute flex flex-col items-center">
                <span className="text-4xl md:text-5xl font-black">{summary.totalAverageScore.toFixed(1)}</span>
                <span className="text-[10px] font-bold opacity-60 tracking-widest uppercase mt-1">Score / 5.0</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Analysis Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Category Scores Table */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white p-8 rounded-[32px] border border-surface-border shadow-sm">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-xl font-black text-text-title flex items-center gap-3">
                <BarChart3 className="w-6 h-6 text-brand-primary" />
                Competency Breakdown
              </h2>
              <div className="flex items-center gap-4 text-xs font-bold uppercase tracking-wider text-text-subtitle">
                <span className="flex items-center gap-1.5"><div className="w-3 h-3 bg-brand-primary rounded-full" /> Others</span>
                <span className="flex items-center gap-1.5"><div className="w-3 h-3 bg-surface-border rounded-full" /> Self</span>
              </div>
            </div>

            <div className="space-y-8">
              {summary.scores.map((score, idx) => {
                const selfScore = summary.selfScores.find(s => s.categoryName === score.categoryName)?.averageScore || 0;
                return (
                  <div key={idx} className="space-y-3">
                    <div className="flex justify-between items-end">
                      <span className="text-sm font-black text-text-title tracking-tight">{score.categoryName}</span>
                      <div className="flex items-center gap-3">
                        <span className="text-xs font-bold text-text-subtitle">Self: {selfScore.toFixed(1)}</span>
                        <span className="text-lg font-black text-brand-primary">{score.averageScore.toFixed(1)}</span>
                      </div>
                    </div>
                    <div className="relative h-3 bg-surface-base rounded-full overflow-hidden">
                      {/* Self Score Marker */}
                      <div 
                        className="absolute top-0 left-0 h-full bg-surface-border z-10 opacity-50"
                        style={{ width: `${(selfScore / 5) * 100}%` }}
                      />
                      {/* Aggregate Score Bar */}
                      <div 
                        className="absolute top-0 left-0 h-full bg-brand-primary rounded-full shadow-sm shadow-brand-primary/30 z-20"
                        style={{ width: `${(score.averageScore / 5) * 100}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Qualitative Feedback */}
          <div className="bg-white p-8 rounded-[32px] border border-surface-border shadow-sm">
            <h2 className="text-xl font-black text-text-title flex items-center gap-3 mb-8">
              <MessageCircle className="w-6 h-6 text-brand-primary" />
              Detailed Feedback
            </h2>
            <div className="space-y-6">
              {summary.detailedComments.map((comment, idx) => (
                <div key={idx} className="group p-6 rounded-3xl bg-surface-base/30 border border-surface-border/50 hover:border-brand-primary/20 hover:bg-white transition-all duration-300">
                  <div className="flex items-start justify-between gap-4 mb-3">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-white flex items-center justify-center border border-surface-border">
                        <Star className="w-4 h-4 text-brand-primary fill-brand-primary" />
                      </div>
                      <div>
                        <span className="text-xs font-black text-brand-primary uppercase tracking-wider bg-brand-primary/5 px-2 py-0.5 rounded-md">
                          {comment.evaluatorRole}
                        </span>
                        <span className="text-xs text-text-subtitle font-bold ml-2">Rating: {comment.score}/5</span>
                      </div>
                    </div>
                    <span className="text-[10px] font-bold text-text-subtitle uppercase tracking-widest bg-white border border-surface-border px-2 py-1 rounded-md">
                      {comment.categoryName}
                    </span>
                  </div>
                  <p className="text-sm text-text-title font-medium italic leading-relaxed">
                    "{comment.comment}"
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Sidebar Insights */}
        <div className="space-y-8">
          <div className="bg-white p-8 rounded-[32px] border border-surface-border shadow-sm">
            <h3 className="font-black text-text-title mb-6 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-brand-primary" />
              Quick Insights
            </h3>
            <div className="space-y-6">
              <div className="p-4 rounded-2xl bg-surface-base/50">
                <p className="text-xs font-bold text-text-subtitle uppercase tracking-widest mb-1">Top Strength</p>
                <p className="text-sm font-black text-text-title">
                  {summary.scores.reduce((prev, curr) => prev.averageScore > curr.averageScore ? prev : curr).categoryName}
                </p>
              </div>
              <div className="p-4 rounded-2xl bg-surface-base/50">
                <p className="text-xs font-bold text-text-subtitle uppercase tracking-widest mb-1">Total Average</p>
                <div className="flex items-end gap-2">
                  <span className="text-2xl font-black text-brand-primary">{summary.totalAverageScore.toFixed(1)}</span>
                  <span className="text-xs font-bold text-text-subtitle mb-1">/ 5.0</span>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-brand-primary/5 p-8 rounded-[32px] border border-brand-primary/10 relative overflow-hidden group">
            <div className="absolute -top-10 -right-10 w-32 h-32 bg-brand-primary/10 rounded-full blur-2xl group-hover:scale-150 transition-transform duration-700" />
            <h3 className="font-black text-brand-primary mb-4 flex items-center gap-2 relative z-10">
              <ShieldCheck className="w-5 h-5" />
              Confidentiality
            </h3>
            <p className="text-xs text-text-subtitle leading-relaxed font-medium relative z-10">
              This report contains aggregated feedback to protect evaluator anonymity. Manager feedback may be identifiable depending on organization structure. Use these insights for your professional growth and development.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

const ClockIcon = ({ className }: { className?: string }) => (
  <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
  </svg>
);

export default MyFeedbackSummary;
