// services/api.ts
import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQueryWithReauth } from "./baseQueryWithReauth";

export const api = createApi({
  reducerPath: "api",
  baseQuery: baseQueryWithReauth,
  tagTypes: [
    "Employee",
    "Profile",
    "Department",
    "Role",
    "JobLevel",
    "Position",
    "EmployeeDepartment",
    "Permission",
    "RoleLevelPermission",
    "ContinuousFeedback",
    "FeedbackTag",
    "OneOnOneMeeting",
    "FeedbackReply",
    "MeetingComment",
    "PIP",
    "PipObjective",
    "PipProgress",
    "PipReview",
    "Form",
    "Cycle",
    "Appraisal",
    "Teams",
    "TeamMembers",
    "EmployeeTeams",
    "Library",
    "GoalSet",
    "Progress",
    "Score",
    "Category",
    "FinancialYear",
    "PerformanceCategory",
    "Feedback360Request",
    "Feedback360Summary",
    "Feedback360Preview",
    "ScoringPolicy",
    "Competency",
    "Nomination",
  ],
  endpoints: () => ({}),
  // This adds more context to traces
  keepUnusedDataFor: 60,
});
