spring.application.name=epms_backend

spring.datasource.url=jdbc:mysql://localhost:3306/epms_test
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=GmP9kLz0aQ7wXvVtHs4YpCqR1nT5mB8sZjF2dEhUdfe3DEse

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=977b6214577c7e
spring.mail.password=7946a06d425b62
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port = 8080